apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data-claim
  namespace: logs
spec:
  storageClassName: elastic-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: elastic-daya