apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  cluster.name: logs-elastic
  network.host: "0.0.0.0"
  discovery.type: single-node
  ELASTIC_USERNAME: "aaaaaaa"
  ELASTIC_PASSWORD: "aaaaaaa"
  discovery.zen.ping.unicast.hosts: elasticsearch-cluster
  xpack.security.enabled: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  ELASTICSEARCH_HOSTS: "http://elasticsearch-loadcalancer.logs:81"
  ELASTICSEARCH_USERNAME: "aaaaaaa"
  ELASTICSEARCH_PASSWORD: "aaaaaaa"
  xpack.security.enabled: "true"