apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
spec:
  selector:
    matchLabels:
      app: elasticsearch
      tier: elasticsearch
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: elasticsearch
        track: stable
    spec:
      volumes:
      - name: elastic-data
        persistentVolumeClaim:
          claimName: elastic-data-claim
      containers:
      - name: elasticsearch
        image: elasticsearch:7.8.1
        envFrom:
        - configMapRef:
            name: es-config
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: elastic-data
          mountPath: data

