apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  selector:
    matchLabels:
      app: elasticsearch
      tier: kibana
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: kibana
        track: stable
    spec:
      containers:
      - name: kibana
        image: kibana:7.8.1
        envFrom:
        - configMapRef:
            name: kibana-config
        ports:
        - containerPort: 5601
          name: kibana-http

