apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-loadcalancer
  namespace: logs
spec:
  selector:
    app: elasticsearch
    tier: elasticsearch
  ports:
  - name: http
    port: 81
    targetPort: 9200
  - name: http-transport
    port: 82
    targetPort: 9300
  type: LoadBalancer
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-loadcalancer
  namespace: logs
spec:
  selector:
    app: elasticsearch
    tier: kibana
  ports:
  - name: http
    port: 9601
    targetPort: 5601
  type: LoadBalancer
  externalTrafficPolicy: Cluster


