apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data
  namespace: logs
  labels:
    type: local
spec:
  storageClassName: elastic-data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/elastic-data"